server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
bank.payment.url=http://localhost:8080/payments
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false