package com.checkout.payment.gateway.enums;

public enum ValidationErrorCode {
  CARD_NUMBER_REQUIRED,
  CARD_NUMBER_INVALID_LENGTH,
  CARD_NUMBER_NON_NUMERIC,
  EXPIRY_MONTH_REQUIRED,
  EXPIRY_MONTH_INVALID,
  EXPIRY_YEAR_REQUIRED,
  EXPIRY_DATE_IN_PAST,
  EXPIRY_DATE_INVALID,
  CURRENCY_REQUIRED,
  CURRENCY_INVALID_LENGTH,
  CURRENCY_NOT_SUPPORTED,
  AMOUNT_REQUIRED,
  AMOUNT_INVALID,
  AMOUNT_TOO_LARGE,
  CVV_REQUIRED,
  CVV_INVALID_LENGTH,
  CVV_NON_NUMERIC
}
